Update CryptoNoteConfig.h
cryptonotefoundation/cryptonote pull request #199
Opened 2018-02-26 08:40 UTC by philkuda

2018-03-07 08:02 UTC, maxsam4 requested changes
These are changes you make to your coin, these are not supposed to be submitted to the upstream.

2018-03-07 08:42 UTC, FndNur1Labs commented
Geez

On Mar 7, 2018 3:02 PM, "Mudit Gupta" <notifications@github.com> wrote:

> *@maxsam4* requested changes on this pull request.
>
> These are changes you make to your coin, these are not supposed to be
> submitted to the upstream.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cryptonotefoundation/cryptonote/pull/199#pullrequestreview-101834086>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AK51tcmPgoJlFgzOuCTaYQPRrKmDVQ2Pks5tb5P9gaJpZM4SS2nj>
> .
>

2018-03-09 03:43 UTC, gsquaredxc commented
Please delete!

2018-03-09 03:48 UTC, closed without merging

2018-03-09 12:47 UTC, gsquaredxc commented
Thanks!